### ISSUE TITLE
Convert issue

### ISSUE THREAD

**Issue by whogit** [eramella/QFXparser#1]
I am pretty much a novice at C# and also to github so perhaps the issue I am seeing is completely due to my ignorance.  

I think that I have imported your QFXparser package correctly.  I created the Statement and Transaction classes.  I have a simple WPF form using OpenFileDialog to select a QFX file.  This all seems to work and I can display the text in a textbox.

However, when I try to parse the text with FileParser, I am having an issue converting the "parser" to a Statement "result".  It says: Cannot implicitly convert type 'QFXparser Statement' to 'readQFX.Statement'.

"readQFX" being the name of my solution.

I zipped up my code and included it if you are interested.  (The error is seen on line 43 of the MainWindows.xaml.cs) I will keep working on it and see if I have simply made a mistake.  Thanks for your QFXparser project.  

[readQFX.zip](https://github.com/eramella/QFXparser/files/2019610/readQFX.zip)

**Comment by eramella** [comment]
Thank you for checking out QFXparser.
You do not need to create the Statement and Transaction classes, these are part of the QFXparser package and already available to you with `using QFXparser;` . I noted them in them in the readme for you to know the type of object that it is returned by the library.
In your case just change this:
`Statement result = parser.BuildStatement();`
to this:
`var result = parser.BuildStatement();`
and it should work.

By using var you are letting the compiler infer the type to the `result` variable which is now of type `QFXparser.Statement` instead `readQFX.Statement`.

Let me know if this solves it.

**Comment by whogit** [comment]
Oh of course!  That makes sense.  In fact, as soon as I deleted my classes the error went away.

Right now I am getting an exception on that line when it executes but let me look at my work again.

Thanks so much for pointing out my mistake!

**Comment by eramella** [comment]
I hope your exception issue. I will closed this issue for now, if you need help let me know.
