### ISSUE TITLE
Unable to install on a 4.5.2 framework project

### ISSUE THREAD

**Issue by BobFrankston** [eramella/QFXparser#2]
**Error** Could not install package 'QFXparser 1.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I'll see if I can learn more.

**Comment by eramella** [comment]
Hi Bob,
thank you for contacting me.
This package targets .NET standard 2.0 which in turns supports the full .NET framework from version 4.6.1 and up. Check this page: [https://docs.microsoft.com/en-us/dotnet/standard/net-standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) 
I would suggest to retarget your application to .NET 4.6.1 if you can.
Let  me know if this helps.
