### ISSUE TITLE
Non-static method requires a target

### ISSUE THREAD

**Issue by drogars** [eramella/QFXparser#3]
I loaded up the nuget package into LinqPad 5 and attempted to run the following code from the read me:

```
var parser = new FileParser(@"C:\test.qfx");
var statement = parser.BuildStatement();
```

But I get an exception, "Non-static method requires a target".

**Comment by eramella** [comment]
Thank you for downloading QFXparser!
I tested it on my desktop with LinqPad but I could not find the issue:

![image](https://user-images.githubusercontent.com/11827066/51432531-38c34b00-1bee-11e9-9aa2-0bf34d4e7f0b.png)

Could it be some LinqPad settings? Did you try it with Visual Studio? Just to see where the issue might be. Also, make sure "C:\test.qfx" exists and it is reachable.
One last thing, you can download the nuget package here https://www.nuget.org/api/v2/package/QFXparser/1.2.0 then open it with a .zip extractor, drill down to qfxparser.1.2.0.nupkg\lib\netstandard2.0\ and get the DLL. Then reference the dll with LinqPad and see if it works (that is what I did in the example above as my version of LinqPad does not allow to reference nuget).
Let me know.

**Comment by drogars** [comment]
I did also try it Visual Studio and got the same error and the file definitely exists.  I managed to get the file to open using an OFX parsing nuget package as the file formats seem to be quite similar; however, it incorrectly interpreted the Name and Memo fields.  I am beginning to wonder if the source of the file (my bank) isn't producing a valid qfx format.  I also exported a .qbo file and  got the same result.  I will have spend some time scrubbing the file before I can send it to you to test.  Maybe the fastest thing would be to clone your repo and debug it and see where it crashes.  What would be the most useful to you?

**Comment by drogars** [comment]
I cloned your source code and opened a file with your test application and got the same exception.  It crashed on line 105 of QFXparser.cs:

`property.SetValue(_statement, token.Content);`

because the `_statement` property is null.  I will start working on creating a scrubbed version of the file that still reproduces the error so I can upload it to you.

**Comment by eramella** [comment]
Best would be the file. You can open it with a text editor and delete the
content of the tags that is sensitive

**Comment by eramella** [comment]
Thx

**Comment by drogars** [comment]
Took some time, but I was able to remove some fields and redact others and still get the same exception.  Hopefully, it helps you.

```OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX>
<BANKMSGSRSV1>
<STMTTRNRS>
<TRNUID>0
<STATUS>
<CODE>0
<SEVERITY>INFO
<MESSAGE>SUCCESS
</STATUS>
<STMTRS>
<CURDEF>USD
<BANKACCTFROM>        
<BANKID>123456789        
<ACCTID>1234567890123
<ACCTTYPE>CHECKING
</BANKACCTFROM>
<BANKTRANLIST>
<DTSTART>20190110120000
<DTEND>20190111120000
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20190110120000
<DTUSER>20190110120000
<DTAVAIL>20190110120000
<TRNAMT>-245.31       
<FITID>1234567890        
<REFNUM>12345678901234
<SIC>000000
<NAME>1st transaction from
<MEMO>bob dylan ACH DEBIT
</STMTTRN>
<STMTTRN>
<TRNTYPE>CHECK
<DTPOSTED>20190110120000
<DTUSER>20190110120000
<DTAVAIL>20190110120000
<TRNAMT>-246.00
<FITID>1234567891
<CHECKNUM>1234
<REFNUM>1234567890
<SIC>000000
<NAME>CHECK
<MEMO>#1234
</STMTTRN>
</BANKTRANLIST>
<LEDGERBAL>
<BALAMT>300.41
<DTASOF>20190119120000
</LEDGERBAL>
<AVAILBAL>
<BALAMT>300.41
<DTASOF>20190119120000
</AVAILBAL>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
```

**Comment by eramella** [comment]
Fixes to missing statement tags and Date parsing has been made. Check out and test latest Nuget package release and let me know if it works. If all is ok, kindly give this project a star.
Thank you!

**Comment by drogars** [comment]
I was able to load the test file above and a full month of transactions from my bank.  Thanks for the help.
